using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace JK.Fixed.Generation;

[Generator]
public sealed class FixedSerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> classDeclaration = context.SyntaxProvider
            .ForAttributeWithMetadataName("JK.Fixed.Configuration.FixedSerializableAttribute",
                 predicate: static (s, _) => true,
                 transform: static (ctx, _) => GetSymbol(ctx));

        context.RegisterSourceOutput(classDeclaration,
            static (spc, source) => Execute(spc, source));
    }

    private static INamedTypeSymbol GetSymbol(GeneratorAttributeSyntaxContext ctx)
        => (INamedTypeSymbol)ctx.TargetSymbol;

    private static void Execute(SourceProductionContext context, INamedTypeSymbol typeSymbol)
    {
        try
        {
            var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : typeSymbol.ContainingNamespace.ToString();
            var name = typeSymbol.Name;
            var serializerClassName = $"{name}FixedSerializer";

            PropertyMetadata[] props = typeSymbol.GetPropertyMetadata();

            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using JK.Fixed.Configuration;");
            sb.AppendEmptyLine();
            sb.AppendNamespace(ns);
            sb.AppendLine($"public static class {serializerClassName}");
            sb.AppendOpenCurlyLine(); // start class
            DeserializeMethodHelpers.Generate(sb, props, name);
            sb.AppendEmptyLine();
            SerializeMethodHelpers.Generate(sb, props, name);
            sb.AppendEmptyLine();
            sb.AppendCloseCurlyLine(); // end class

            context.AddSource(
                $"{ns ?? "Global"}.{serializerClassName}.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8)
            );
        }
        catch (Exception ex)
        {
            DiagnosticDescriptor descriptor = new(
                id: "FXGEN001",
                title: "Fixed serializer generator error",
                messageFormat: "Fixed serializer generator failed: {0}",
                category: "JK.Fixed.Generation",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true);

            Diagnostic diagnostic = Diagnostic.Create(descriptor, Location.None, ex.Message);
            context.ReportDiagnostic(diagnostic);
        }
    }
}
