using System.Text;
using JK.Fixed.SourceGenerators.Helpers;
using Microsoft.CodeAnalysis.Text;

namespace JK.Fixed.SourceGenerators;

[Generator]
public sealed class FixedSerializerGenerator : IIncrementalGenerator
{
    private const string generatorNamespace = "JK.Fixed.SourceGenerators";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ClassTypeInfo> classDeclaration = context.SyntaxProvider
            .ForAttributeWithMetadataName($"{generatorNamespace}.FixedSerializableAttribute",
                 predicate: static (s, _) => true,
                 transform: static (ctx, _) => GetClassInfo(ctx));

        context.RegisterSourceOutput(classDeclaration,
            static (spc, source) => Execute(spc, source));
    }

    private static ClassTypeInfo GetClassInfo(GeneratorAttributeSyntaxContext ctx)
    {
        var type = (INamedTypeSymbol)ctx.TargetSymbol;
        var classInfo = new ClassTypeInfo(type);
        return classInfo;
    }

    private static void Execute(SourceProductionContext context, ClassTypeInfo classInfo)
    {
        StringBuilder sb = new();

        if (!string.IsNullOrEmpty(classInfo.Namespace))
        {
            sb.AppendLine("");
            sb.AppendLine($"namespace {classInfo.Namespace};");
            sb.AppendLine("");
        }

        var serializerClassName = $"{classInfo.Name}FixedSerializer";
        var className = $"{classInfo.Namespace}.{classInfo.Name}";

        // deserialize line to item
        // {{className}} item = new {{className}}();
        // parser.Parse(line);

        // serialize item to line
        // BuildLine(item, fixedProperties);

        sb.Append(
            $$"""
            // <auto-generated>
            using System.Collections.Generic;
            using System.Text;
            public static class {{serializerClassName}}
            {
                //public static IEnumerable<{{className}}> Deserialize(IEnumerable<string> lines)
                //{
                //    foreach (var line in lines)
                //    {
                //        yield return null; // TODO: implement deserialization
                //    }
                //}
                //
                //public static IEnumerable<string> Serialize(IEnumerable<{{className}}> items)
                //{
                //    foreach ({{className}} item in items)
                //    {
                //        //StringBuilder sb = new StringBuilder();
                //        yield return ""; // sb.ToString();
                //    }
                //}
            }
            """);

        context.AddSource(
            $"{generatorNamespace}.{serializerClassName}.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8)
        );
    }
}
